# Generated by Django 4.0.6 on 2022-12-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('PR', 'Personal'), ('DR', 'Doctor')], default=None, max_length=2),
        ),
    ]
