# Generated by Django 4.0.6 on 2022-12-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('PR', 'Personal'), ('DR', 'Doctor')], max_length=2),
        ),
    ]
