# Generated by Django 4.0.6 on 2022-12-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0004_doctor_patient_report_patient_report_patient_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='timings',
            new_name='service_time',
        ),
    ]
