# Generated by Django 4.0.6 on 2022-12-27 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0005_rename_timings_doctor_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='Doc_Appoint.report'),
        ),
    ]
