# Generated by Django 4.0.6 on 2022-12-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0006_alter_patient_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='doctor_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='patient_name',
        ),
    ]
