# Generated by Django 4.0.6 on 2022-12-31 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_booked_name', to='Doc_Appoint.doctor'),
        ),
    ]
