# Generated by Django 4.0.6 on 2023-01-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0009_patient_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='study',
            field=models.TextField(),
        ),
    ]
