# Generated by Django 4.0.6 on 2023-01-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0012_alter_doctor_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='service_time_from',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='service_time_to',
            field=models.IntegerField(),
        ),
    ]
