# Generated by Django 4.0.6 on 2023-01-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0013_alter_doctor_service_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='service_time_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='service_time_to',
            field=models.DateTimeField(),
        ),
    ]
