# Generated by Django 4.0.6 on 2023-01-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0018_alter_doctor_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='patient',
            field=models.ManyToManyField(blank=True, default=[0], related_name='doctors_patients', to='Doc_Appoint.patient'),
        ),
    ]
