# Generated by Django 4.0.6 on 2023-01-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0019_doctor_phone_number_alter_doctor_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
