# Generated by Django 4.0.6 on 2023-01-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0020_doctor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
