# Generated by Django 4.0.6 on 2023-01-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0023_alter_doctor_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='service_time_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='service_time_to',
            field=models.DateTimeField(null=True),
        ),
    ]
