# Generated by Django 4.0.6 on 2023-01-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0024_alter_doctor_service_time_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='service_time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='service_time_to',
            field=models.TimeField(null=True),
        ),
    ]
