# Generated by Django 4.0.6 on 2023-01-17 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0028_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='report',
        ),
        migrations.AddField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='patient_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
