# Generated by Django 4.0.6 on 2023-01-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0029_remove_patient_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
