# Generated by Django 4.0.6 on 2023-01-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0030_patient_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='patient_phone_number',
        ),
    ]
