# Generated by Django 4.0.6 on 2023-01-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0032_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(max_length=7),
        ),
    ]
