# Generated by Django 4.0.6 on 2023-01-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0035_alter_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_report_by_appointment', to='Doc_Appoint.report'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
