# Generated by Django 4.0.6 on 2023-01-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_Appoint', '0036_appointment_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='medication',
        ),
        migrations.AlterField(
            model_name='report',
            name='written_report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
